name: CI - build and lint

on:
  pull_request:
    branches:
      - main

env:
  PNPM_STORE: "/pnpm-store"
  TURBO_DISABLE_TELEMETRY: 1
  TURBO_SCM_BASE: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || github.event.before }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  VERSION: ${{ github.sha }}

jobs:
  monorepo:
    name: Build monorepo
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Cache next.js
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/apps/web/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('./pnpm-lock.yaml') }}-${{ hashFiles('./apps/web/**/*.js', './apps/web/**/*.jsx', './apps/web/**/*.ts', './apps/web/**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('./pnpm-lock.yaml') }}-

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm exec turbo run ci --affected

      - name: Lint
        run: pnpm lint:md && pnpm exec turbo lint --affected
